language: go
go:
  - 1.8.x

env:
  - NODE=1

before_install:
  - go get github.com/googollee/go-socket.io
  - go get github.com/zhouhui8915/go-socket.io-client
  - go run ./app/main.go

script:
  - sleep 1

notifications:
  email:
    on_failure: change
